config/routes.rb
Rails.application.routes.draw do
  root to: "statics#home"

  get "about" => "statics#about", as: :about
  get "contact" => "statics#contact", as: :contact
  
  namespace :admin do
    root to: "users#index"
    resources :users
    resources :categories
    resources :words
  end

  resources :users, except: [:index, :destroy]
  get "sign_up" => "users#new", as: :sign_up
  
  resources :categories, only: [:index]

  resources :words, except: :show

  resources :lessons, except: [:new, :edit, :destroy]

  resources :results, only: :index

  resource :sessions, only: [:new, :create, :destroy]
  get "sign_in" => "sessions#new", as: :sign_in
  get "sign_out" => "sessions#destroy", as: :sign_out
  

end

app/models/word.rb
class Word < ActiveRecord::Base
  has_one :lesson_word
  belongs_to :category
  has_many :word_answers, inverse_of: :word, dependent: :destroy
  accepts_nested_attributes_for :word_answers
  
  validates_presence_of :content, :category_id

  scope :learned, ->(user_id, category_id) do
    lesson_word_ids = LessonWord.select("word_id")
        .where("user_id = ? AND word_answer_id IS NOT NULL", user_id).to_sql
    unless category_id.blank?
      Word.where "id IN (#{lesson_word_ids}) AND category_id = ?", category_id
    else
      Word.where "id IN (#{lesson_word_ids})"
    end
  end

  scope :not_learned, ->(user_id, category_id) do
    lesson_word_ids = LessonWord.select("word_id")
      .where("user_id = ? AND word_answer_id IS NULL", user_id).to_sql
    unless category_id.blank?
      Word.where "id IN (#{lesson_word_ids}) AND category_id = ?", category_id
    else
      Word.where "id IN (#{lesson_word_ids})"
    end
  end

  scope :search, ->(content) do
    where("content LIKE ?", "%#{content}%")
  end

  scope :unique, ->(user, category) do
    used_word_ids = LessonWord.select(:word_id)
                              .where("user_id = ? AND category_id = ?",
                                      user.id, category.id)
                              .to_sql
    where "id NOT IN (#{used_word_ids}) AND category_id = ?", category.id
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :admin_auth
  before_action :set_word, only: [:show, :edit, :update, :destroy]

  def index
    if params[:category_id].blank?
      @words = Word.search(params[:content])
                   .paginate page: params[:page], per_page: 20
    else
      category = Category.find params[:category_id]
      @words = category.words.search(params[:content])
                       .paginate page: params[:page], per_page: 20
    end
  end

  def show
  end

  def new
    @word = Word.new
    4.times { @word.word_answers.build }
  end

  def create
    @word = Word.new word_param
    if @word.save
      flash[:success] = "A new word has been added."
      redirect_to admin_words_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @word.update_attributes word_param
      flash[:success] = "Update successfull."
      redirect_to admin_words_path
    else
      render "edit"
    end
  end

  def destroy
    @word.destroy
    flash[:success] = "A word has been deleted."
    redirect_to admin_words_path
  end

  private

    def set_word
      @word = Word.find params[:id]
    end

    def word_param
      params.require(:word).permit(:content, :category_id,
            word_answers_attributes: [:content, :correct])
    end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :user_auth

  def index
    if params[:learn] == "all" || params[:learn].blank?
      if params[:category_id].blank?
        @words = Word.all.paginate page: params[:page], per_page: 20
      else
        category = Category.find params[:category_id]
        @words = category.words.paginate page: params[:page], per_page: 20
      end
    elsif params[:learn] == "learned"
      @words = Word.learned(current_user.id, params[:category_id])
              .paginate page: params[:page], per_page: 20
    else
      @words = Word.not_learned(current_user.id, params[:category_id])
              .paginate page: params[:page], per_page: 20
    end
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_form.html.erb
<%= form_for [:admin, @word] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div><%= f.label :content %>
  <%= f.text_field :content, autofocus: true %></div>
  
  <div><%= f.label :category %>
  <%= f.select :category_id, Category.all.map { |category| [category.name, category.id] },
        {prompt: "Select Category"} %></div>
  
  <div id="word_answers">
    <h3>Word Answers</h3>
    <%= f.fields_for :word_answers do |word_answer_form| %>
      <div><%= word_answer_form.label :content %>
      <%= word_answer_form.text_field :content %></div>

      <div class="radio"><%= word_answer_form.radio_button :correct, true %>
      <%= word_answer_form.label :correct %></div>
    <% end %>
  </div>

  <div><%= f.submit label, class: "btn btn-primary" %>
  <%= link_to "Cancel", words_path, class: "btn" %></div>
<% end %>

app/views/admin/words/_word.html.erb
<tr>
  <td><%= word.id %></td>
  <td><%= word.content %></td>
  <td><%= word.word_answers.corrected.try(:content) %></td>
  <td><%= link_to "Edit", edit_admin_word_path(word) %>
  <%= link_to "Delete", admin_word_path(word),
      data: { method: :delete, confirm: "Are you sure?" } %></td>
</tr>

app/views/admin/words/edit.html.erb
<% provide :title, "Admin | Edit Word" %>

<div class="span4 offset4">
  <h1>Edit Word</h1>
  <br />
  <%= render "form", label: "Save" %>
</div>

app/views/admin/words/index.html.erb
<% provide :title, "Admin | Word" %>

<div id="word_list">
  <div class="row">
    <div class="span12">
      <%= form_tag admin_words_path, { method: :get } do %>
        <div><span>Category</span>
        <%= select_tag "category_id",
            options_from_collection_for_select(Category.all, "id", "name",
                                          selected: params[:category_id]),
                                          { prompt: "Select Category" } %></div>
        <div><%= text_field_tag "content", params[:content],
              placeholder: "Search", autofocus: true %></div>
        <div><%= submit_tag "Search", class: "btn btn-primary", name: nil %></div>
      <% end %>
      <%= will_paginate @words %>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Word</th>
            <th>Meaning</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
          <%= render @words %>
        </tbody>
      </table>
      <%= link_to "New Word", new_admin_word_path, class: "btn btn-medium btn-primary" if admin? %>
    </div>
  </div>
</div>

app/views/admin/words/new.html.erb
<% provide :title, "Admin | New Word" %>

<div class="span4 offset4">
  <h1>New Word</h1>
  <br />
  <%= render "form", label: "Add Word" %>
</div>