config/routes.rb
Rails.application.routes.draw do
  root to: "statics#home"

  get "about" => "statics#about", as: :about
  get "contact" => "statics#contact", as: :contact
  
  namespace :admin do
    root to: "users#index"
    resources :users
    resources :categories
    resources :words
  end

  resources :users, except: [:index, :destroy]
  get "sign_up" => "users#new", as: :sign_up
  
  resources :categories, only: [:index]

  resources :words, except: :show

  resources :lessons, except: [:new, :edit, :destroy]

  resources :results, only: :index

  resource :sessions, only: [:new, :create, :destroy]
  get "sign_in" => "sessions#new", as: :sign_in
  get "sign_out" => "sessions#destroy", as: :sign_out
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons, dependent: :destroy
  has_many :words, dependent: :destroy
  
  validates_presence_of :name
  validates_uniqueness_of :name

  scope :search, ->(name) { where "name LIKE ?", "%#{name}%" }

  def results
    lessons.map(&:result).inject(:+) || 0
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :admin_auth
  before_action :set_category, except: [:index, :new, :create]

  def index
    @categories = Category.search(params[:name]).paginate page: params[:page], per_page: 20
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_param
    if @category.save
      flash[:success] = "A new category has been added."
      redirect_to admin_categories_path
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_param
      flash[:success] = "Update successfull."
      redirect_to admin_categories_path
    else
      render "edit"
    end
  end

  def destroy
    @category.destroy
    flash[:success] = "A category has been deleted."
    redirect_to admin_categories_path
  end

  private

    def set_category
      @category = Category.find params[:id]
    end

    def category_param
      params.require(:category).permit(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :user_auth
  
  def index
    @categories = Category.all.paginate page: params[:page], per_page: 20
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_category.html.erb
<tr>
  <td><%= category.id %></td>
  <td><%= category.name %></td>
  <td><%= category.description %></td>
  <td>
    <%= link_to "Edit", edit_admin_category_path(category) %>
    <%= link_to "Delete", admin_category_path(category),
    data: { method: :delete, confirm: "Are you sure?" } %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category] do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div><%= f.label :name %>
  <%= f.text_field :name, autofocus: true %></div>
  
  <div><%= f.submit label, class: "btn btn-primary" %>
  <%= link_to "Cancel", admin_categories_path, class: "btn" %></div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, "Admin | Edit Category" %>

<h1>Edit Category</h1>
<br />
<%= render "form", label: "Save" %>

app/views/admin/categories/index.html.erb
<% provide :title, "Admin | Categories" %>

<div id="word_list">
  <div class="row">
    <div class="span12">
      <%= form_tag admin_categories_path, {method: :get} do %>
        <div><span>Name: </span><%= text_field_tag "name",
              params[:name], placeholder: "Search", autofocus: true %></div>
        <div><%= submit_tag "Search", class: "btn btn-primary", name: nil %></div>
      <% end %>
      <%= will_paginate @categories %>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Description</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
          <%= render @categories %>
        </tbody>
      </table>
      <%= link_to "New Category", new_admin_category_path, class: "btn btn-medium btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, "Admin | New Category" %>

<h1>New Category</h1>
<br />
<%= render "form", label: "Add Category" %>