config/routes.rb
Rails.application.routes.draw do
  root to: "statics#home"

  get "about" => "statics#about", as: :about
  get "contact" => "statics#contact", as: :contact
  
  namespace :admin do
    root to: "users#index"
    resources :users
    resources :categories
    resources :words
  end

  resources :users, except: [:index, :destroy]
  get "sign_up" => "users#new", as: :sign_up
  
  resources :categories, only: [:index]

  resources :words, except: :show

  resources :lessons, except: [:new, :edit, :destroy]

  resources :results, only: :index

  resource :sessions, only: [:new, :create, :destroy]
  get "sign_in" => "sessions#new", as: :sign_in
  get "sign_out" => "sessions#destroy", as: :sign_out
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :password_not_require

  has_many :lessons, dependent: :destroy
  has_many :lesson_words, dependent: :destroy
  
  mount_uploader :avatar, AvatarUploader
  
  before_save -> { self.email.downcase! }
  before_destroy -> { remove_avatar! }
  
  validates_presence_of :username, :email
  validates_uniqueness_of :username, :email
  validates_format_of :email, with: /[^@\s]+@[\w\-_\.]+\.\w{2,4}/i
  validates_length_of :password, minimum: 6, unless: :password_not_require
  
  has_secure_password

  scope :search, ->(name) { where "username LIKE ?", "%#{name}%" }

  def self.digest(string)
    BCrypt::Password.create string
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    self.password_not_require = true
    update_attributes! remember_digest: User.digest(remember_token)
    self.password_not_require = false
  end

  def forget
    self.password_not_require = true
    update_attributes! remember_digest: nil
    self.password_not_require = false
  end

  def authenticated?(remember_token)
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def signed_up_at
    created_at.strftime "%h %d, %Y %l:%M %p"
  end
  
  def last_updated_at
    updated_at.strftime "%h %d, %Y %l:%M %p"
  end

  def activities
    lessons.order "updated_at DESC"
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_auth
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.search(params[:name]).paginate page: params[:page], per_page: 20
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new user_param
    if @user.save
      flash[:success] = "You have successfully signed up!"
      redirect_to admin_users_path
    else
      render "new"
    end
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @user.update user_param
      flash[:success] = "Profile has been successfully updated!"
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "A user has been deleted."
    redirect_to admin_users_path
  end

  private

    def set_user
      @user = User.find params[:id]
    end

    def user_param
      params.require(:user).permit(:username, :email,
                    :password, :password_confirmation,
                    :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :user_auth, except: [:new, :create]
  before_action :current_user_auth, only: [:show, :edit, :update]
  before_action :admin_auth, only: [:index, :destroy]
  before_action :redirect_signed_in_user, only: [:new, :create]
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new user_param
    if @user.save
      flash[:success] = "You have successfully signed up!"
      sign_in @user
      redirect_to @user
    else
      render "new"
    end
  end
  
  def show
    @lessons = current_user.activities.paginate page: params[:page], per_page: 20
  end
  
  def edit
  end
  
  def update
    if @user.update user_param
      flash[:success] = "Profile has been successfully updated!"
      redirect_to @user
    else
      render "edit"
    end
  end
  
  private
  
    def set_user
      @user = User.find params[:id]
    end
    
    def user_param
      params.require(:user).permit(:username, :email,
                    :password, :password_confirmation,
                    :avatar)
    end
    
    def current_user_auth
      unless current_user?(params[:id])
        flash[:error] = "Permission denied!"
        redirect_to root_path
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], html: { class: "form" } do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div><%= f.label :username %>
  <%= f.text_field :username, autofocus: true %></div>
  
  <div><%= f.label :email %>
  <%= f.email_field :email %></div>
  
  <div><%= f.label :password %>
  <%= f.password_field :password %></div>
  
  <div><%= f.label :password_confirmation, "Confirm" %>
  <%= f.password_field :password_confirmation %></div>
  
  <div><%= f.label :avatar, "Choose your avatar" %>
  <%= f.file_field :avatar %></div><br />
  
  <div><%= f.submit label, class: "btn btn-primary" %></div>
<% end %>

app/views/admin/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= link_to user.username, admin_user_path(user) %></td>
  <td><%= user.email %></td>
  <td><%= user.admin? ? "Admin" : "User" %></td>
  <td><%= user.signed_up_at %></td>
  <td><%= user.last_updated_at %></td>
  <td><%= link_to "Edit", edit_admin_user_path(user) %>
      <%= link_to "Delete", admin_user_path(user),
          data: { method: :delete, confirm: "Are you sure?" } %></td>
</tr>

app/views/admin/users/edit.html.erb
<% provide :title, "Admin | Edit User" %>

<div class="span4 offset4">
  <h1>Edit User's Profile</h1>
  <br />
  <%= render "form", label: "Save" %>
</div>

app/views/admin/users/index.html.erb
<% provide :title, "Admin | Users" %>

<div id="word_list">
  <div class="row">
    <div class="span12">
      <%= form_tag admin_users_path, { method: :get } do %>
        <div><span>Name: </span><%= text_field_tag "name",
              params[:name], placeholder: "Search", autofocus: true %></div>
        <div><%= submit_tag "Search", class: "btn btn-primary", name: nil %></div>
      <% end %>
      <%= will_paginate @users %>
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Username</th>
            <th>Email</th>
            <th>Created at</th>
            <th>Updated at</th>
            <th>Options</th>
          </tr>
        </thead>
        <tbody>
          <%= render @users %>
        </tbody>
      </table>
      <%= link_to "New User", new_admin_user_path, class: "btn btn-meduim btn-primary" %>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<% provide :title, "Admin | New User" %>

<div class="span4 offset4">
  <h1>Create User</h1>
  <br />
  <%= render "form", label: "Create User" %>
</div>

app/views/admin/users/show.html.erb
<% provide :title, "Admin | Show User" %>

<div id="profile" class="span4">
  <div>
    <p>
      <%= image_tag asset_path(@user.avatar.url),
          width: "100px", height: "130px", alt: "Profile Image" %>
      <label><%= @user.username %></label>
    </p>
    <p><label>Email:</label>
    <span><%= @user.email %></span></p>
    <p><label>Created at:</label>
    <span><%= @user.signed_up_at %></span></p>
    <p><label>Updated at::</label>
    <span><%= @user.last_updated_at %></span></p>
  </div>
</div>